### ISSUE TITLE
Aqara Vibration Sensor stopped working after Update to .86

### ISSUE THREAD

**Issue by peer69** [dresden-elektronik/deconz-rest-plugin#3455]
## Describe the bug

After Update to .86 and FW 26660700 using ConBee II the Aqara Vibration Sensor stopped working. It did not send any commands, at least none of them were visible in Phoscon or deCONZ GUI. 
I have tried repairing it but it seems like the device is not fully recognized anymore. GUI does recognize it as vibration sensor and it builds the cluster correctly from what I can see but no data is shown via Phoscon or API. I can see the sensor flashing blue in GUI when it is triggered but it never updates. I tried a second sensor but it doesnt work either. 
## Steps to reproduce the behavior

1. Pair sensor via Phoscon GUI
  2. Wait for pairing to complete 
  3. Click on sensor
  4. No data is shown neither is via API
## Expected behavior

 Vibration events should be recognized and shown. 
## Screenshots
 
<img width="728" alt="image" src="https://user-images.githubusercontent.com/28559804/96592912-37561380-12e9-11eb-8013-05bf9bbc006c.png">

<img width="197" alt="image" src="https://user-images.githubusercontent.com/28559804/96592889-2f966f00-12e9-11eb-854c-c3631dabf151.png">

## Environment

 - Host system: Ubuntu 16.04 
 - Running method: ESXI 6.7
 - Firmware version: (26660700)
 - deCONZ version: (2.05.86)
 - Device: (ConBee II)
 - Do you use an USB extension cable: (yes) -- only relevant for ConBee I/II
 - Is there any other USB or serial devices connected to the host system? If so: Which? no.

**Comment by Mimiix** [comment]
What happens if you click the button on it?

**Comment by peer69** [comment]
Device in GUI flashing blue. Nothing to see in phoscon or via API.

**Comment by peer69** [comment]
I have just downgraded to .83. It works again. Seems to be a bug with the never build.

**Comment by Agratam** [comment]
2.05.84 works too.
I had issues with 2.05.86.

Host system: Ubuntu 20.04
Firmware version: (26660700)
deCONZ version: (2.05.86)
Device: (ConBee II)
Do you use an USB extension cable: (yes) -- only relevant for ConBee I/II
Is there any other USB or serial devices connected to the host system? If so: Which? Yes. Aeotec Zwave Stick

**Comment by Mimiix** [comment]
@Agratam Do you specifically mean that everything works EXCEPT the vib sensor?

**Comment by Agratam** [comment]
Yes, everything else works. i.e.:
Tradfri Lights and Switches
Aqara Temperature and Motion sensors

**Comment by Mimiix** [comment]
Alright, thanks :)

**Comment by Mimiix** [comment]
I've created a internal issue. I'll have this addressed.

**Comment by SAOPP** [comment]
Yes guys still broken vibros...

**Comment by FunkOdyssey2001** [comment]
I have this issue in 2.05.85 and 2.05.86.

**Comment by SAOPP** [comment]
@FunkOdyssey2001 yes dat right, it's beginb from 95th beta.

**Comment by FunkOdyssey2001** [comment]
I am not really a developer, but in 2baf9573f18035fc182fa67fa8c4662e2fa50bd2 there were several lines deleted.
I could not find similar lines in the current code for lumi.vibration. But again: I don't know if this is right or wrong. :-)

**Comment by nikbr998** [comment]
Just confirming that I also have the issue. 2.05.85/26390500/Conbee1 (Marthoc container).

**Comment by Mimiix** [comment]
**No need for others adding "i have it too". It is known**

**Comment by ebaauw** [comment]
For reasons only known by Xioami, this sensor uses the _Door Lock_ cluster.  Probably adding support for one of the locks broke support for the vibration sensor.

**Comment by manup** [comment]
I'll make some tests later on with debugger to see where it fails.

**Comment by Mimiix** [comment]
Will be fixed in new beta! :)

**Comment by SAOPP** [comment]
Thanks guys for quick fix it.

**Comment by FunkOdyssey2001** [comment]
Is this fix working for you?
I don't see any new values.

**Comment by Mimiix** [comment]
NEed to wait for the new release or compile it yourself @FunkOdyssey2001  ;)

**Comment by FunkOdyssey2001** [comment]
That's what I did. 
A current checkout, compiled and copied.

**Comment by SwoopX** [comment]
With the change made by @manup, you don't need to compile the plugin. Just replace the `general.xml` from the pulled repo with the version running on your system. Otherwise, that file will just be overwritten with by a new release package.

**Comment by FunkOdyssey2001** [comment]
I am sorry. You are absolutely right. It is working fine with the fixed xml. Sorry.

**Comment by SwoopX** [comment]
Np, glad we got confirmation.

**Comment by cracyfloyd** [comment]
i was going back to version 84 and now it works again.

**Comment by sophof** [comment]
Thanks for point me to this thread. I replaced the general.xml file and can confirm that the sensor is currently working. One sensor is not currently picked up by Home Assistant, but that could be due to my previous tinkering, I expect it to work once I re-add it.

**Comment by timbru31** [comment]
While my sensors initially showed data again after repairing them (I’ve had the very very binding), the stop working after a while (time ranges from hours to days). It seems the same as #2581 and #2591 - I suspect the sensitivity values changes and thus breaks my use case (window open detection)

They remain available in the GUI and the API shows a lastseen timestamp, however the updated value does not match, nor detects it the correct vibration.

**Comment by manup** [comment]
Is this with a version [v2.5.87](https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/v2.5.87) or later?
The vibration sensor got a fix in there, just checked mine with v2.6.0 it is working.

**Comment by timbru31** [comment]
I could've sworn that I was on .87, but apt says it's still .86. Going to test v2.6.0 and will report back (once it either works fine for a longer period or when one becomes buggy again).

Btw ConBee II with FW 26660700

**Comment by aberkeley** [comment]
Hi i am on 2.0.8 with FW 26680700 Conbee ii. my sensor appears in deconz but isnt recognised nor is it appear in Phoscon (as you would expect)

![image](https://user-images.githubusercontent.com/73428191/102771764-5e2ed580-437e-11eb-8c47-0e4182922828.png)

![image](https://user-images.githubusercontent.com/73428191/102772442-66d3db80-437f-11eb-8378-be5bda06eaf0.png)

**Comment by SwoopX** [comment]
The device is not paired correctly/completely.

**Comment by aberkeley** [comment]
> The device is not paired correctly/completely.

thx swoop - removed and re-pair all working now thx

**Comment by Mimiix** [comment]
@peer69 As others reported it works again, can you confirm that it was fixed for you too?

**Comment by aberkeley** [comment]
Hi - as of today i can report i now have the same issue. Having got the item working (thx swoopX) with a re-pairing. I had to move the device (so i deleted it and then attempted to re-add) - this is successful- now i get the same as the original poster:

![image](https://user-images.githubusercontent.com/73428191/102920738-2b223a00-4483-11eb-84b5-1f6df0081508.png)

the sensor is fine on deconz vnc view:

![image](https://user-images.githubusercontent.com/73428191/102920787-3d03dd00-4483-11eb-90e2-0b45a4baf24d.png)

2.0.8 with FW 26680700

**Comment by SwoopX** [comment]
Your device node descriptor looks odd. You might want to give this a try:
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Xiaomi:-Lost-devices-or-functional-issues

**Comment by bcutter** [comment]
Still not tracked down/fixed? Will implement one of those sensors shortly and don´t want to spend hours to find out "jap, same issue" :-)

**Comment by bcutter** [comment]
Two of those are working just fine related to this issue.

They sometimes trigger without an actual movement/vibration ("phantom vibration" if that issue got not a name yet) which is pretty annoying.

But nothing substantial to add for this issue.

**Comment by jjdave2002** [comment]
I do not have that phantom trigger, mine are once triggering and then always stayed in "vibration" mode, so they do NOT reset the vibration detection after the vibration was gone. Everything was fine until the update of the FW (which is neede for the zugbe 3.0 sensors). Any other ideas? Curious as they sensor are named as "door lock", or not?

**Comment by manup** [comment]
Closing as the vibration sensor is now handled via DDF and received various fixes.
