### ISSUE TITLE
Tuya Double Switch TS0012 turns itself off again.

### ISSUE THREAD

**Issue by schumi2004** [dresden-elektronik/deconz-rest-plugin#3693]
## Describe the bug
Connected the wired double Tuya switch (no-neutral) switch as described and paired it with Deconz (Home Assistant).
When turned on manually or via Deconz the switch tunrs itself off again after approximatly 2 min.
Looks like some timer got activated but can't find any documentation about it.

And sometimes, after it happened for a few times, it becomes unresponsive and only manual activation makes it work again.

## Steps to reproduce the behavior
Connect the switch as instructed, pair it with Deconz and just turn it on, manually or using Deconz/Home Assistant.

## Expected behavior
Just stay on.

## Screenshots
n/a

## Environment
 - Host system: Raspberry Pi 3B+
 - Running method: Home Assistent deCONZ Add-on
 - Firmware version: 26660700
 - deCONZ version: 2.05.88 / 15-10-2020
 - Device: ConBee II
 - Do you use an USB extension cable: yes
 - Is there any other USB or serial devices connected to the host system? If so: Which? SSD

- switch used: 2 gang switch TS0012

## deCONZ Logs
Need to figure out how to save the logs to a file in HassIO.

## Additional context
n/a

**Comment by Smanar** [comment]
Hello, can you make a try with the api disabled ? Plugin / rest API plugin.

**Comment by schumi2004** [comment]
I'm not sure how to do this?
I checked the Home Assistant Add-on: deCONZ in my HassIO setup but can't find anything to disable api?

I removed the port in HA deCONZ addon configuration that disables API backend, is that what you mean?
![image](https://user-images.githubusercontent.com/968545/99434262-dd0f9900-290e-11eb-844d-358b8578796e.png)

For now, I unpaired the switch and it functions normal again as a regular switch.
Will pair it again later this evening when I have more time.
Is it also possible I caused this behavior using a combination of button presses?
At first, I thought it did not pair so I tried it again to find out they were added underneath the lights section. Maybe a reset of the switch (if possible?) will help also?

**Comment by Smanar** [comment]
Ha, sorry it s only possible using the GUI.

It s possible too with removing the lib file from the folder, but I don't want to broke your setting. Was to make the same test than you, the device in the network but without the API, to check if it s from zigbee or api side.

For the rest, idk, never see a timer feature in this kind of switches. Perhaps something visible in log (you have it in phosocn too now, in "help")

**Comment by megawubs** [comment]
@schumi2004 Not really related to the topic, but where did you got this switch? I've been searching for something like this for a while now. But can't really find any shop selling this when I search for it on the web.

**Comment by schumi2004** [comment]
@megawubs https://nl.aliexpress.com/item/4000298926256.html?cv=47843

@Smanar 
The HassIO deCONZ addon does have a GUI.
I can choose from Phoscon or Deconz, i'll check again when i have some more time inbetween work.

**Comment by Smanar** [comment]
>The HassIO deCONZ addon does have a GUI.
I can choose from Phoscon or Deconz, i'll check again when i have some more time inbetween work.

Ha ? are you sure of that ?
But if you have the deconz GUI
![dfgdf](https://user-images.githubusercontent.com/20152487/99563998-2cff6600-29ca-11eb-9c99-6b366ed923d1.png)

**Comment by schumi2004** [comment]
Got it unchecked, going to test it now.
![image](https://user-images.githubusercontent.com/968545/99592670-ca6d9080-29f0-11eb-9c4b-e3f381f6bd7e.png)

**Comment by Smanar** [comment]
You can pair it, and disable the switch after, or just let it already paired.
It s just to check if you have the same issue with the api disabled, only with the zigbee network alone. The important part is not pairing, but to check if you still have the "timer" bug.

**Comment by schumi2004** [comment]
Switch still functions as expected since yesterday. The only difference is that I only did the pairing procedure once and not twice as the first time. 
I think that the very first time I paired the switch and thought it did not work I activated some feature during second attempt that caused this auto off. I took 2 minutes every time it turned itself off (used a timer to measure) and because of that I think something got activated during pairing when it already was.

Yesterday when I wanted to test I already had deleted the device and I needed to enable REST API again for it to get paired and since then it works flawless.

Maybe we should close this issue for now and reopen when I have new devices with similar behavior.

**Comment by Smanar** [comment]
This is no documentatin with the device ? even in chinese ?

**Comment by schumi2004** [comment]
Documentation is shipped with it but doesn't describe "advances" features like auto off or something like that (if any). It only describes how to wire and pair it for different versions (neutral, no neutral, wifi, zigbee, rf433)

![1605897359206525293823412038649](https://user-images.githubusercontent.com/968545/99837297-a7b1b800-2b67-11eb-8cb9-b0e0b19d055c.jpg)
![16058973843093859530211622480297](https://user-images.githubusercontent.com/968545/99837327-b4cea700-2b67-11eb-940a-73f7ccd94991.jpg)
![16058974070791104870117378599184](https://user-images.githubusercontent.com/968545/99837348-bf893c00-2b67-11eb-8257-8e343a105f32.jpg)

**Comment by kind3r** [comment]
Had the exact same issue, obviously because of the 'double pairing'. I thought that you have to pair each gang individually.

Deleted the switch from Phoscon app (removing one light removes the other also) and then repaired and now it's ok. I'm thinking I should do this with some of the other sensors that sometimes missbehave.

**Comment by kind3r** [comment]
I think I spoke too soon, after some time they started automatically turning off again ...

**Comment by Smanar** [comment]
I have perhaps an idea for tuya, but not sure It's that, because I have the ame bug on different brands.
Can you confirme me, this device use tuya cluster ?
Just enable log in deconz, press a button, and give me the lines with "debug tuya", all lines pls,  even if there are in double.

**Comment by kind3r** [comment]
I'm not sure what log types need to be activated and what version (I'm running 2.5.88), but my switch is identified as `_TZ3000_fvh3pjaz` or `Heiman`:

```
20:21:50:962 DB sql exec REPLACE INTO nodes (id, state, mac, name, groups, endpoint, modelid, manufacturername, swbuildid, ritems) 
VALUES ('13', 'normal', 'bc:33:ac:ff:fe:f5:b4:db-01', 'Baie', '65520', '1', 'TS0012', '_TZ3000_fvh3pjaz', '', '{"attr/id":"13","attr/lastannounced":null,"attr/lastseen":"2020-12-08T18:21Z","attr/manufacturername":"_TZ3000_fvh3pjaz","attr/modelid":"TS0012","attr/name":"Baie","attr/swversion":null,"attr/type":"On/Off light","attr/uniqueid":"bc:33:ac:ff:fe:f5:b4:db-01","state/alert":null,"state/on":true,"state/reachable":true}')
20:21:50:965 DB sql exec REPLACE INTO nodes (id, state, mac, name, groups, endpoint, modelid, manufacturername, swbuildid, ritems) 
VALUES ('14', 'normal', 'bc:33:ac:ff:fe:f5:b4:db-02', 'Hol', '65520', '2', '', 'Heiman', '', '{"attr/id":"14","attr/lastannounced":null,"attr/lastseen":"2020-12-08T18:21Z","attr/manufacturername":"Heiman","attr/modelid":null,"attr/name":"Hol","attr/swversion":null,"attr/type":"On/Off light","attr/uniqueid":"bc:33:ac:ff:fe:f5:b4:db-02","state/alert":null,"state/on":false,"state/reachable":true}')
2
``` 

What I noticed is that after pairing it works fine for a few hours and then randomly switches to the auto-off behaviour.

**Comment by Smanar** [comment]
You haven't the GUI ?

Yo have not line starting with "Tuya debug X" when using a button ?

**Comment by kind3r** [comment]
As most of the people out there I'm using a Conbee 2 via the Home Assistant addon. More specifically HASS.io on a PI 4. I do have access to the deCONZ app via VNC but can't copy paste from there and finding something in there is a pain. I can use docker logs from the host, but I need to enable the logs in the addon's config. I have enabled `dbg_info: 2` but I found nothing Tuya related.

**Comment by k0rn3l** [comment]
I have just installed two new switches: https://www.aliexpress.com/item/4000298926256.html
I have the same issue with auto-off after 2-3 minutes on both (X711A and X712A models). I have paired them only once.
Deconz plugin 2.07.01 / 8.12.2020 with home assistant
Conbee 2 FW: 26660700

**Comment by k0rn3l** [comment]
I did some further investigation...
I did factory reset of the node from deconz vnc app; paired it again; and at first it looked like the problem was gone when I was switching the light ON from home assistant. It stayed ON. But as soon as I used the switch button, the problem returned and now the light turns itself off after 2 minutes no matter if I use home assistant or the button to turn the light on.
Deconz log from self turn off event:
`01:30:39:194 DeviceAnnce of LightNode: 0xbc33acfffeedfc0f Permit Join: 0
01:30:40:197 ZCL attribute report 0xBC33ACFFFEEDFC0F for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
01:30:40:289 verified group capacity: 255 and group count: 1 of LightNode 0xbc33acfffeedfc0f
01:30:40:290 0xbc33acfffeedfc0f found group 0xFFF0
01:30:41:758 binding for cluster 0x0006 of 0xBC33ACFFFEEDFC0F exists (verified by reporting)
01:30:41:758 skip configure report for cluster: 0x0006 attr: 0x0000 of node 0xBC33ACFFFEEDFC0F (seems to be active)
01:30:54:023 ZCL attribute report 0xBC33ACFFFEEDFC0F for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000
`

**Comment by k0rn3l** [comment]
Workaround:
Following info on https://zigbee.blakadder.com/Lonsonho_X711A.html
I forced entering pairing mode (10s button press) when already paired with ZB network, then I clicked "Add new lights" in Phoscon app, switch repaired with the same network and is now working correctly.

**Comment by kind3r** [comment]
I noticed the same behaviour with the latest firmware, I left the switch unpaired for a week, yesterday I paired it again, after that I rebooted my PI and it was gone, so did a re-pair (altho the switch lights showed that it was paired) and it showed up again in Phoscon and HA with the names that I previously set and it's been working fine since. Usually it takes up to 2h for the auto-off behaviour to kick in, but now it seems to be fine for the past 20h.

**Comment by Smanar** [comment]
Ha yesssss, thx a lot, It help so much, I was totaly lost, no idea at all.

> It seems like there’s two versions of this switch coming from AliExpress. The TS0011 appears to turn off by itself after two minutes after being paired for the first time with ZHA. To get it to function correctly after pairing the first time, press and hold the switch for 10s to enter pairing mode and then press ‘Add Devices Via This Device’ in your Zigbee Coordinator in Home Assistant. After that, it should function correctly.

**Comment by gregskh** [comment]
Hello,

I have TS0011 and TS0012 switches and They turned off after 2 minutes no matter if I use home assistant or the button to turn the light on. After this procedure everything works ok:

It seems like there’s two versions of this switch coming from AliExpress. The TS0011 appears to turn off by itself after two minutes after being paired for the first time with ZHA. To get it to function correctly after pairing the first time, press and hold the switch for 10s to enter pairing mode and then press ‘Add Devices Via This Device’ in your Zigbee Coordinator in Home Assistant. After that, it should function correctly.

Original source: https://zigbee.blakadder.com/Lonsonho_X711A.html

**Comment by parowa92** [comment]
Same here.
`01:18:38:486 DeviceAnnce of LightNode: 0xbc33acfffe7720c2 Permit Join: 0
01:18:38:487 DeviceAnnce of LightNode: 0xbc33acfffe7720c2 Permit Join: 0
01:18:39:470 verified group capacity: 255 and group count: 1 of LightNode 0xbc33acfffe7720c2
01:18:39:470 0xbc33acfffe7720c2 found group 0xFFF0
01:18:40:219 verified group capacity: 255 and group count: 1 of LightNode 0xbc33acfffe7720c2
01:18:40:219 0xbc33acfffe7720c2 found group 0xFFF0
01:18:40:904 ZCL attribute report 0xBC33ACFFFE7720C2 for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
01:18:41:025 ZCL attribute report 0xBC33ACFFFE7720C2 for cluster: 0x0006, ep: 0x02, frame control: 0x08, mfcode: 0x0000 
01:18:47:604 Current channel 15
01:18:47:612 Device TTL 4506 s flags: 0x7
01:18:53:965 ZCL attribute report 0xBC33ACFFFE7720C2 for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
01:18:54:084 ZCL attribute report 0xBC33ACFFFE7720C2 for cluster: 0x0006, ep: 0x02, frame control: 0x08, mfcode: 0x0000 
01:19:03:090 binding for cluster 0x0006 of 0xBC33ACFFFE7720C2 exists (verified by reporting)
01:19:03:091 skip configure report for cluster: 0x0006 attr: 0x0000 of node 0xBC33ACFFFE7720C2 (seems to be active)
01:19:34:091 binding for cluster 0x0006 of 0xBC33ACFFFE7720C2 exists (verified by reporting)
01:19:34:092 skip configure report for cluster: 0x0006 attr: 0x0000 of node 0xBC33ACFFFE7720C2 (seems to be active)`

**Comment by Smanar** [comment]
And have you done the procedure ?

**Comment by parowa92** [comment]
Yes, but if i disable api i cant use Tradfri 5 button remote, so it's not a solution for me.
`10:47:07:613 Device TTL 2865 s flags: 0x7
10:47:15:112 DeviceAnnce of LightNode: 0xbc33acfffe7720c2 Permit Join: 0
10:47:15:113 DeviceAnnce of LightNode: 0xbc33acfffe7720c2 Permit Join: 0
10:47:16:099 verified group capacity: 255 and group count: 1 of LightNode 0xbc33acfffe7720c2
10:47:16:099 0xbc33acfffe7720c2 found group 0xFFF0
10:47:16:845 verified group capacity: 255 and group count: 1 of LightNode 0xbc33acfffe7720c2
10:47:16:845 0xbc33acfffe7720c2 found group 0xFFF0
10:47:17:280 ZCL attribute report 0xBC33ACFFFE7720C2 for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
10:47:17:396 ZCL attribute report 0xBC33ACFFFE7720C2 for cluster: 0x0006, ep: 0x02, frame control: 0x08, mfcode: 0x0000 
10:47:31:127 ZCL attribute report 0xBC33ACFFFE7720C2 for cluster: 0x0006, ep: 0x01, frame control: 0x08, mfcode: 0x0000 
10:47:31:249 ZCL attribute report 0xBC33ACFFFE7720C2 for cluster: 0x0006, ep: 0x02, frame control: 0x08, mfcode: 0x0000 
10:47:39:091 binding for cluster 0x0006 of 0xBC33ACFFFE7720C2 exists (verified by reporting)
10:47:39:092 skip configure report for cluster: 0x0006 attr: 0x0000 of node 0xBC33ACFFFE7720C2 (seems to be active)
10:47:47:658 	0xBC33ACFFFE7720C2 force poll (2)
10:47:47:663 ZCL attribute report 0xBC33ACFFFE7720C2 for cluster: 0x0006, ep: 0x01, frame control: 0x18, mfcode: 0x0000 `

**Comment by Smanar** [comment]
Disable the API ?
Nope, the procedure to remove this situation, on this model.

**Comment by parowa92** [comment]
I tried to pair it again, after pairing. Next i tried this on ZHA, stil same problem. I just moved to z2mqtt and its gone.
When i disabled api the switches still was working, but with this problem.

**Comment by kind3r** [comment]
After 10 days of working fine they suddenly started to turn off again (after a reboot, but it was not the first during those 10 days). I have tried double re-pairing (3 times) but still the issue of them turning off by themselfes comes back after some time (1-2 hours).

**Comment by parowa92** [comment]
> After 10 days of working fine they suddenly started to turn off again (after a reboot, but it was not the first during those 10 days). I have tried double re-pairing (3 times) but still the issue of them turning off by themselfes comes back after some time (1-2 hours).

Try zigbee2mqtt, today i switched from deconz and it is working flawless.

**Comment by kind3r** [comment]
Indeed, I have also tried ZHA and get the same auto-off behaviour, but from the start (in deConz most of the time it takes a few hours for the switch to start turning off).
I installed Z2M yesterday and it's been working flawlesly ever since, even pairing all the other devices was a smoother experience. The only thing I noticed that it's a bit less responsive than deConz, but I think this is because of the timeouts (`adapter_delay`) that are not properly set in the driver so I have created a PR for it.

**Comment by notovich** [comment]
having the same issue, seems hardware issue, as switch was auto off after 2m and 2s exactly, no matter what i'm doing it is turning off, tried deleting/rairing/re-pairing nothing helps, it drives me crazy.

**Comment by Smanar** [comment]
And that don't  work for you too ?

> It seems like there’s two versions of this switch coming from AliExpress. The TS0011 appears to turn off by itself after two minutes after being paired for the first time with ZHA. To get it to function correctly after pairing the first time, press and hold the switch for 10s to enter pairing mode and then press ‘Add Devices Via This Device’ in your Zigbee Coordinator in Home Assistant. After that, it should function correctly.

**Comment by Rem-me** [comment]
Hello,
My two cents about this issue : 
I have baught several zigbee tuya switches from amazon/yagusmart and aliexpress/zemismart and it seems I got two familly of switches: 

- one with _TYZB01_* manufacturer, which has no problem, has no light when it's switched off (even if paired) and has a red light when switched on
- one with _TZ3000_* manufacturer, which works as expected for a couple of hours after been paired, and then switches off by itself after two minutes and 2 or 3 seconds. When not paired, it shows no light if it is off, and red light if on (like the TYZB01). When paired, it shows green light if off, and orange if on. 

I've got both TYZB01 and TZ3000 from amazon/yagusmart (in one sending !) and only TZ3000 (2 month later) from zemismart. The two kinds have the exact same packaging. Maybe it's a change of internal design for the same product.

![SwitchZemismartPb](https://user-images.githubusercontent.com/76900897/103476100-1e6ee180-4db3-11eb-9f48-226bf8c3c6d8.jpg)

Under deConz, TZ3000 has  a "time" cluster not present on TYZB01
![DifferencesUnderDeconz](https://user-images.githubusercontent.com/76900897/103476316-d2bd3780-4db4-11eb-90ef-1940976346d2.JPG)
 
I noticed several things about the TZ3000 : 

- In deConz or Phoscon Web UI, unpair the switch ("delete device") removes the green light (ok, not a surprise) and removes the auto-off behavior.
- Once the auto-off appeared, physically disconnecting the gateway (plug off the conbee 2 usb key) doesn't change anything. It's like the switches had been put in a sticky state (even with power supply cut)
- After an auto switch off, if you switch on for, say, 30 secs, then switch off and on again, the switch will turns itself off after 1 min 30 sec... As if there were a counter reset after 2min.
- And last but not least : as soon as paired through zigbee2mqtt (deConz stopped before), the auto-off disapears

**Comment by Smanar** [comment]
Perhaps need to make something with the time cluster ....

**Comment by ffragnol** [comment]
Hello i have exactly the same problem with TZ3000 version. Did you solved it ?

**Comment by notovich** [comment]
Fixed by moving from zha to z2m - please note you can't run both, moving to z2m you will need to re-discover all devices

**Comment by ffragnol** [comment]
It's not a fix for the inital problem. 👎  How get it worked with Deconz ?

**Comment by kind3r** [comment]
I would give Z2M a chance. After the initial accomodation you'll find it much easier to use and it supports more devices and they seem to work better. I had the same reluctance at first but now I'm happy I switched.
It does seem to add a tiny bit of lag, but I think that's because of some artificially introduced delays in their Conbee driver implementation (I have submited a PR to properly configure those).

**Comment by Mimiix** [comment]
@notovich @kind3r  This doesn't help here at all to mention that... Stick on-topic please :)

@Smanar What's the status?

**Comment by notovich** [comment]
@Mimiix did you try to run it on Z2M? meaning disabling deCONZ/ZHA completely and installing Z2M? in my case it fixed the issue, have no idea how, but now over 2 weeks switch working as expected (nocking on wood)

**Comment by kind3r** [comment]
@Mimiix The point is it works in Z2M so @Smanar can check how they handle pairing this device and what exceptions they put in for it (if that's the case) and take inspiration from there. Debugging Deconz stuff is especially difficult for those of us running HASS on PIs.

**Comment by Mimiix** [comment]
@notovich Z2M is not deCONZ... So your reply is not related to this issue. 

@kind3r I agree on that. It might help Smanar 👍

**Comment by kind3r** [comment]
@Mimiix it is not but it works with their adapter (I'm using a ConBee II), so at least this excludes the firmware.

**Comment by Smanar** [comment]
@Mimiix, I realy don't have idea, It seem this issue is only present on deconz. The device can work for some time, then have the bug.

And if user disable the bind, the device continue to send request.

I think I will make a hack to disable the second request if there is 2 time the same request in less than 1s. No better idea ATM.

We are working on the time cluster too on anther issue, but I don't see how this cluster can provoke this kind of issue.

**Comment by kind3r** [comment]
@Smanar the issue is also present in ZHA.

To sum up (all tested with ConBee II):
- **ZHA** - auto off behaviour right after pairing
- **deConz** - auto off behaviour starts from pairing or after some time (few hours)
- **Z2M** - no auto off behaviour

So deConz is somewhere in between, not good, not bad, 3.6 :D :D :D

**Comment by Smanar** [comment]
Ha yep, sorry I mix 2 issue.
The auto off and the double event. I was speaking about the double event one.

To disable the auto off the solution in link don't work at all  ?

> It seems like there’s two versions of this switch coming from AliExpress. The TS0011 appears to turn off by itself after two minutes after being paired for the first time with ZHA. To get it to function correctly after pairing the first time, press and hold the switch for 10s to enter pairing mode and then press ‘Add Devices Via This Device’ in your Zigbee Coordinator in Home Assistant. After that, it should function correctly.

**Comment by parowa92** [comment]
> Ha yep
> To disable the auto off the solution in link don't work at all ?
> 
> > It seems like there’s two versions of this switch coming from AliExpress. The TS0011 appears to turn off by itself after two minutes after being paired for the first time with ZHA. To get it to function correctly after pairing the first time, press and hold the switch for 10s to enter pairing mode and then press ‘Add Devices Via This Device’ in your Zigbee Coordinator in Home Assistant. After that, it should function correctly. 

This solution is for ZHA, tell me where i can find 'add devices via this device' in deconz. 

Now its 17 days since i moved from deconz to z2mqtt. 
This bug is only on ZHA and Deconz.

**Comment by kind3r** [comment]
For me in ZHA re-pairing trick did not work. It did sometimes work in deConz but only for a few hours.

**Comment by expend20** [comment]
Hello all! 

I have exactly the same problem but with 3 gang device TS0013. The device turns off by itself after ~2 minutes. The seller says the solution is to rejoin, but it didn't work to me either. Any ideas?

Here are my logs of joining, enabling and auto off parts: https://pastebin.com/JxsjVU40

**Comment by arislaz** [comment]
I am not sure if I am helping a lot but the guys over the smartthings community has a similar issue with this switches. Either solution is around choosing the type of the switch when pairing. Maybe someone with more experience can check it out.

**Comment by degrammont** [comment]
Hello I'm facing the same issue with my two 3 Gang switches (TZ3000_wyhuocal / TS0013)
I had the issue 7 days ago but it was working well for a week (using deconz docker container). I tried to install another device in my config and the issue came back.
Reseting the device (searching for new lights without removing it from the config) helps for the moment but I don't know how long it will stay like that.

**Comment by cellfride** [comment]
Hi, I have the same issue with TS0012 even if i'm using zigbee2mqtt, the switch turns off randomly after some time, i tried the 10 seconds reset and pairing the switch again but it didn't solve the issue

**Comment by HakunaMatmata** [comment]
Same issue here, with Deconz and ZHA did not try zigbee2mqtt yet as i do not have a clue how to set it up on home-assistant (no extension catalog with zigbee2mqtt).
I tried repairing it worked once but after a power cut problem came back and impossible to get it working with a new pairing.

**Comment by Smanar** [comment]
There will be soon a corrective for button event for switch > https://github.com/dresden-elektronik/deconz-rest-plugin/pull/4265

It correct the "double event" bug, and perhaps the "auto power off" one, if someone can test it ?

**Comment by HakunaMatmata** [comment]
> There will be soon a corrective for button event for switch > #4265
> 
> It correct the "double event" bug, and perhaps the "auto power off" one, if someone can test it ?

would be glad to do so, how to download beta version?

**Comment by Smanar** [comment]
It s little bit more complicated to test it ^^
The PR is not validated, so you need an unix machine and complile the code (I can explain how to to do)

**Comment by HakunaMatmata** [comment]
Ok let me know then.
I use a QNAP with Deconz and Home assistant both installed via docker.
I began switching to ZHA (home assistant embedded version) but same problem there.

**Comment by Smanar** [comment]
The procedure is described here > https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz-development-package-optional-linux-only

```
sudo apt install deconz-dev
git clone --branch tuya https://github.com/sebres/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

But it s realy hard to do that on docker, and I m not able to do that.
You need a linux machine with a linux OS complete.

**Comment by k0rn3l** [comment]
I managed to compile the plugin from  the mentioned PR  #4265  (I've compiled it inside of docker container running the deconz plugin in my hassio instance :P )
I replaced the original plugin, and after restarting deconz and repairing my light switch ( Vendor _TZ3000_9hpxg80k
Model TS0011 ) I am getting normal behaviour for now. But this is fresh, I need to wait for a few hours to confirm the auto-off behaviour is really gone.

**Comment by duges53** [comment]
I have the same problem.
Do any of you have news on a possible solution please?

**Comment by Mimiix** [comment]
@Smanar

**Comment by Smanar** [comment]
IDK, the patch used for the double event is not working.
I haven't found more information yet about this issue. Perhaps something to do with the time cluster ...

**Comment by Palthe** [comment]
I have the same problem with my Model TS0011. The lights go out after 2 minutes. 
However, when I go to the deCONZ app and press "Read node descriptor" on the device after booting up my system, the problem disappears. 
![deCONZ](https://user-images.githubusercontent.com/79236051/108292886-c9d1cb00-7194-11eb-9a2d-af43f597d0fd.jpg)

**Comment by Smanar** [comment]
Ha ?
How many time without the bug ?

**Comment by Palthe** [comment]
Hi Smanar,

Yes, in home assistant, I had a bug with the software. The lights only
worked after reboot of the system when you pressed the button or when you
went into the software and read the node descriptor. Also there is a bug
where the lights go out after two minutes. This is well known on the
internet with the Tuya TS001 see :
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3693

I have removed the phoscon / deconz software in Home Assistant and
installed Zigbee2MQTT and it worked fine.No more bugs. I like the software,
if it can be solved I would probably move back to  phoscon / deconz.

Best regards,

Patrick


Op do 18 feb. 2021 om 17:24 schreef Smanar <notifications@github.com>:

**Comment by pukamakara** [comment]
> Hi, I have the same issue with TS0012 even if i'm using zigbee2mqtt, the switch turns off randomly after some time, i tried the 10 seconds reset and pairing the switch again but it didn't solve the issue

Hi. Did you solve the auto-off problem with z2m only? I have z2m from the very beginning and the two TS0013 switches. Both turn off after 2 mins. Please help me.

**Comment by Smanar** [comment]
No we still have the problem on deconz, but I thought that was solved for z2m.

**Comment by pukamakara** [comment]
> No we still have the problem on deconz, but I thought that was solved for z2m.

As I said before, I have never had deconz installed on my HA. I have z2m, and this switch is turning off after 2 mins.

**Comment by CiTroNaK** [comment]
I have the same issue. I will happily provide any help to fix it (like logs, testing and so on). Thank you!

**Comment by Smanar** [comment]
Ok so it seem there is some news about this issue, from the link just above, it seem we just need to block the Alarm cluster.

The full description https://community.smartthings.com/t/uk-light-switches-my-experiences-2020/196035/64
I haven't understand all the stuff, but it seem on zigby they have just removed the Time cluster.

**Comment by Smanar** [comment]
No one with the device and a linux machine (with real OS) to make a test ?

**Comment by sACLeFR** [comment]
> Ok so it seem there is some news about this issue, from the link just above, it seem we just need to block the Alarm cluster.
> 
> The full description https://community.smartthings.com/t/uk-light-switches-my-experiences-2020/196035/64
> I haven't understand all the requests echnages, but it seem on zigby they have just removed the Time cluster [zigpy/zha-device-handlers#535](https://github.com/zigpy/zha-device-handlers/issues/535) like have have said another user on this issue.
> 
> Someone want to make a try ?

In the post sent days ago https://github.com/zigpy/zha-device-handlers/issues/826
they are talking about a quirks solving the issue. In the replacement, I can see the removal of a time parameter. So it seems linked.
Too newbie to parameter this on my installation so I'm blocked. But we are turning around a time parameter in the signature to disable.

**Comment by Smanar** [comment]
Yeap, even for me it more a hack than a solution. But impossible to found sniff from the original gateway to mimic them

```
On timeout (attrId=0x4001, value=0)
OffWaitTIme (attrId=0x4001, value=0)
0x8001 with value=1
0x8002 with value=0
```

Perhpas with changing this setting direclty on the device using deconz, I can explain how to do
Or I can to make a black list in the API code for the gateway ignore request for the device to the alarm cluster.

**Comment by k0rn3l** [comment]
> No one with the device and a linux machine (with real OS) to make a test ?

I can help with testing. Last time I managed to compile rest plugin inside of docker container running deconz plugin in HA. All  necessary dependencies can be installed temporarily in the container.

**Comment by Smanar** [comment]
Ok so can you take a look on deconz GUI for those param ?
```
On timeout (attrId=0x4001, value=0)
OffWaitTIme (attrId=0x4001, value=0)
```

For me 0 value are good, I don't see problem.

Or code modification

You have the procedure here https://github.com/dresden-elektronik/deconz-rest-plugin#install-deconz-development-package-optional-linux-only
So for you, after having installed deconz :

```
sudo apt install deconz-dev
git clone --branch disable_off https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

If you have a small raspberry,it can freeze during compilation, my pi 3 do, so remove "-j2"

I have ONLY added this device in black list, tell me if you have other one, it disable the time cluster.
- _TZ3000_9hpxg80k

**Comment by k0rn3l** [comment]
Hi again!
The bottom line is: the new code has not resolved self turn off issue.
Details:
The code on the "disable_off" branch does not compile ;) 
I do not know much about cpp but I managed to apply a fix and successfully compile it. I hope it did not change the logic, just added { } around case code.
Here is my patch:
```
diff --git a/de_web_plugin.cpp b/de_web_plugin.cpp
index 8488308e..240edbd7 100644
--- a/de_web_plugin.cpp
+++ b/de_web_plugin.cpp
@@ -954,10 +954,12 @@ void
DeRestPluginPrivate::apsdeDataIndication(const deCONZ::ApsDataIndication &i
             break;
 
         case TIME_CLUSTER_ID:
-            LightNode *lightNodetest =
getLightNodeForAddress(ind.srcAddress(), ind.srcEndpoint());
-            if (lightNodetest && lightNodetest->manufacturer() !=
QLatin1String("_TZ3000_9hpxg80k"))
             {
-                handleTimeClusterIndication(ind, zclFrame);
+              LightNode *lightNodetest =
getLightNodeForAddress(ind.srcAddress(), ind.srcEndpoint());
+              if (lightNodetest && lightNodetest->manufacturer() !=
QLatin1String("_TZ3000_9hpxg80k"))
+              {
+                  handleTimeClusterIndication(ind, zclFrame);
+              }
             }
             break;
````
After compiling and replacing original plugin I restarted deconz. I tried using it with  _TZ3000_9hpxg80k light switch. No luck. I tried to re-pair it. Auto off behavior still returns after 2 ~hours. 
Switch settings was:
0x4001 OnTime: value 0
0x4002 OffWaitTime: value 0

**Comment by Smanar** [comment]
Nope, your code change seem good, have you some device that need the time cluster ?
Else can you try to disable completely this part ? with disabling the line (using comment)

`    //handleTimeClusterIndication(ind, zclFrame);`

**Comment by Smanar** [comment]
No better result with that ?

**Comment by k0rn3l** [comment]
Unfortunately removing this line did not help. Auto-off behavior still exist :(

**Comment by Smanar** [comment]
Ha, I have a better idea, easier

In deconz / edit / network setting, panel "endpoint", on endpoint [1] at inclusters, remove the cluster 0x000A.

It will remove the cluster on the conbee, you will be able to see the difference if you check the clusters list on the conbee (probably need a restart)

Like that, the conbee will not have the time cluster at all. But make the test on a dev machine if you can.

**Comment by Smanar** [comment]
No one have try the last tests ?

**Comment by schumi2004** [comment]
I have not followed it closely but solution for me still is to unlink and repair it in Deconz.

**Comment by Smanar** [comment]
And this procedure is enought to make it working for you ?

**Comment by schumi2004** [comment]
Yes.

With recent HassIO core update 2021.5.1 it broke again and it started to go off again after few minutes. 
Deleted it in Deconz and re-added it again and it was working again.

**Comment by jonnipee** [comment]
hi, just wondering if there is any solution to this issue

**Comment by vitalybrandes** [comment]
> hi, just wondering if there is any solution to this issue

I am using HA with ZHA,.
I fixed it by creating py file.
[This fix my problem](https://github.com/zigpy/zha-device-handlers/issues/826)

**Comment by jonnipee** [comment]
> > hi, just wondering if there is any solution to this issue
> 
> I am using HA with ZHA,.
> I fixed it by creating py file.
> [This fix my problem](https://github.com/zigpy/zha-device-handlers/issues/826)

I will try and see if it helps but i am trying to interface directly to deconz api not using HA :D. ideally hoping for an "official fix"

**Comment by jonnipee** [comment]
> Ha, I have a better idea, easier
> 
> In deconz / edit / network setting, panel "endpoint", on endpoint [1] at inclusters, remove the cluster 0x000A.
> 
> It will remove the cluster on the conbee, you will be able to see the difference if you check the clusters list on the conbee (probably need a restart)
> 
> Like that, the conbee will not have the time cluster at all. But make the test on a dev machine if you can.

Hi - If you remove 0x000A, Save and then Read it comes back. Rebooting doesnt help either. Anything else that we could try?

**Comment by Mimiix** [comment]
Re openeing on request

**Comment by Smanar** [comment]
>Hi - If you remove 0x000A, Save and then Read it comes back. Rebooting doesnt help either. Anything else that we could try?

yes, have made same tests with someone called Alec on discord, It s no more possible, there is a security now on deconz that re-add missing usefull cluster.
So I m seing 3 thing to try:
- Disable the cluster answer, with comment this line on code
```
        case TIME_CLUSTER_ID:
            //handleTimeClusterIndication(ind, zclFrame);
            break;
```
But you need to re-include the device, I think if the device see the cluster on the gateway it s too late.
- Editing code to remove the time cluster, too much hack to do just for a test.
- Try to find the request used by the tuya gateway to prevent this action, because she work fine and with the time cluster.

**Comment by jonnipee** [comment]
hi sanmar - i am willing to try this but i will need some guidance. i am running deconz on windows 10 with conbee. thanks!

**Comment by manup** [comment]
It would be very interesting to sniff the traffic between Tuya gateway and the switch, to see what the gateway does to keep the switch alive. I recon it's a specific command/response.

**Comment by jonnipee** [comment]
ok i will order one tomorrow and see how fast i can get it

**Comment by Smanar** [comment]
On windows 10, it s not possible to compile code, so I presume you want to try the third method ?

The only sniff I have found it s this one https://community.smartthings.com/t/uk-light-switches-my-experiences-2020/196035/64
But we haven't the tuya gateway reaction.

But it s harder you re thinking, you need the tuya gateway, and a sniffer too, I can provide guidance, no hard but you will need some time.

**Comment by jonnipee** [comment]
hi i have a conbee ii and also a cr2531 device - would that be enough?

**Comment by Smanar** [comment]
Sure, It work fine with this device and windows https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html

But you need too the CC debugger to change the firwmare, if you don't have the good one by defaut ?

**Comment by jonnipee** [comment]
i have the debugger and can change the firmware no issue!

**Comment by jonnipee** [comment]
@Smanar ramdom question - i have another tuya switch that appears to have no problem. 
its a Tuya 30A switch

![image](https://user-images.githubusercontent.com/58016593/124505530-4d1a5300-ddfc-11eb-9176-bb372fad6e16.png)

**Comment by Smanar** [comment]
I have find too this page, but on the gived link https://github.com/predshaw/Smartthings I don't see information about a "2mn heartbeat"

**Comment by jonnipee** [comment]
is it possible to compare the differences between the ts0001 and the ts00012? physically they appear very similar?

**Comment by jonnipee** [comment]
> I have find too this page, but on the gived link https://github.com/predshaw/Smartthings I don't see information about a "2mn heartbeat"
> 
> But this issue don't impact all device, and somes user have succesfully included them with multiple inclusion, but I don't know the logic.

i saw this in one of the files
![image](https://user-images.githubusercontent.com/58016593/124510535-9a032700-de06-11eb-9914-918a698946e1.png)

**Comment by Smanar** [comment]
Here you have 2 models, one working and one not working https://github.com/dresden-elektronik/deconz-rest-plugin/issues/3693#issuecomment-753597377

**Comment by jonnipee** [comment]
i know but they are different switches - TYZB01 and TZ3000 mine are both TZ3000
![image](https://user-images.githubusercontent.com/58016593/124510609-ca4ac580-de06-11eb-8f02-b5873604dbf5.png)

**Comment by Smanar** [comment]
Ha ? why I haven't see this line on code ....

But if you want to test this command, just this line to the xml file /usr/share/deCONZ/zcl/general.xml (it s the line between space)

```
      <attribute id="0x0034" name="Device Mode" type="enum8" default="0" access="rw" required="o" mfcode="0x100b">
        <value name="Single Rocker" value="0"></value>
        <value name="Single Push Button" value="1"></value>
        <value name="Dual Rocker" value="2"></value>
        <value name="Dual Push Button" value="3"></value>
      </attribute>

      <attribute id="0x0099" name="Orvibo test" type="u8" default="0x00" access="rw" required="o">

		</attribute-set>
		<attribute-set id="0x4000" description="Manufacturer specific" mfcode="0x1037">
			<attribute id="0x4001" name="128-Bit security key" type="seckey" access="r" required="m" mfcode="0x1037"></attribute>
			<attribute id="0x4002" name="IEEE address" type="uid" access="rw" required="m" mfcode="0x1037"></attribute>
		</attribute-set>
```

Then just restart deconz, you will see new attribute in the attribute table on the basic cluster 0x0000

Try to read it, deconz will say you if this attribute exist or not on this device, and you will be able to change it.

**Comment by jonnipee** [comment]
for win10 would that be: C:\Users\HomeComputer\AppData\Local\deCONZ\zcl\general.xml

**Comment by Smanar** [comment]
Ha yep, sorry, and take care, have edited the previous post recently.

**Comment by jonnipee** [comment]
it did not add the new attribute: this is after restarting and repairing
![image](https://user-images.githubusercontent.com/58016593/124512156-50b4d680-de0a-11eb-898f-8c8f078c9210.png)

Something i noticed - is since i added the 30A switch and it is routing the ts00012 switch through it - it doesnt turn off anymore
also its model id is ts0001 here phoscon still shows ts0012
![image](https://user-images.githubusercontent.com/58016593/124512376-c4ef7a00-de0a-11eb-8e27-b4a9c7280ad4.png)

**Comment by jonnipee** [comment]
well after i unpaired the 30a switch - the problem returned

**Comment by Smanar** [comment]
This code is working, tested on my side

```
				<description>As printed on the product.</description>
			</attribute>
			<attribute id="0x4000" name="SW Build ID" type="cstring" access="r" required="o" range="0,16"></attribute>
		
			<attribute id="0x0099" name="Orvibo test" type="u8" default="0x00" access="rw" required="o"></attribute>
			
			<attribute id="0xff0d" name="Xiaomi Sensitivity" type="u8" access="rw" required="o" mfcode="0x115f"></attribute>
			<attribute id="0xff22" name="Xiaomi Disconnect 1" type="u8" showas="hex" access="rw" required="o" mfcode="0x115f">
				<description>S
```


For the difference, depending of routing, it s realy strange ...
From that I have read, it s based on device<>gateway, not device <>parent.

Both devices are wired switch ? But one of them seem not work as router "office light", can be the difference too.

I have just asked to Manup, to know if it s switch have issue too.

**Comment by jonnipee** [comment]
Hi - yes both switches are wired switches, they have the same appearance on the PCB side. 

will try your code now

**Comment by jonnipee** [comment]
Not sure what to do next :D
![image](https://user-images.githubusercontent.com/58016593/124515255-9759ff00-de11-11eb-9cc8-5544fd168eb3.png)

**Comment by jonnipee** [comment]
Not sure if different application version or power source would make a difference.

![image](https://user-images.githubusercontent.com/58016593/124515701-a55c4f80-de12-11eb-8898-b7b2759f6116.png)
![image](https://user-images.githubusercontent.com/58016593/124515772-d9d00b80-de12-11eb-98a0-df9df8c329a0.png)

**Comment by jonnipee** [comment]
hi @Smanar 
So update:

1. I can sniff traffic now - but will need your support for the encryption keys 
2. I have a tuya gateway
3. I currently have 3 switches (x1 TS0001 (30a Switch), x2 TS0012 2 Gang light switch) 
![image](https://user-images.githubusercontent.com/58016593/124601653-ac2ea500-de9a-11eb-87da-d60254e79ec5.png)
TS0001 is functioning as a router - light 4 only goes via the TS001 and it does not turn off any more, light 6 goes to both the conbee and the ts0001 and it turns off every 2 minutes. 

**Questions**

1. is there a way to change its routing manually to only go via the TS0001 to test?
2. when can we sniff traffic :D

**Comment by jonnipee** [comment]
i also saw that recently tuya opened an integration with HA io dont know if there is any useful information here: 
https://github.com/tuya/tuya-home-assistant?_source=ba73d30e469131a469b65d2fcd68f011

**Comment by jonnipee** [comment]
Capture turning lightswitch (TS0012) on and then it turning itself off (switch directly to conbee)
![image](https://user-images.githubusercontent.com/58016593/124608654-7640ef00-dea1-11eb-87d7-8cdc9154ca58.png)

Capture of lightswitch (TS0012) turning on and staying on (connected via TS0001 switch) after 2 minutes
![image](https://user-images.githubusercontent.com/58016593/124609388-29114d00-dea2-11eb-9027-8a82278f42e5.png)

**Comment by Smanar** [comment]
> Not sure what to do next :D

Nothing ^^, the attribute was disabled by deconz, mean not supported by the device.

>i also saw that recently tuya opened an integration with HA io dont know if there is any useful information here:

If I m right this code use the original gateway and the tuya cloud.

>is there a way to change its routing manually to only go via the TS0001 to test?

Not realy, but it s not a problem.

>I can sniff traffic now - but will need your support for the encryption keys

I think it s ok now ? Or if it s for use with the tuya gateway, you just need to include a device when wireshark is enabled, he will catch itself the key.

About the sniff you displayed:
-I suppose the magic is between the gateway and the device so can use as filter
`zbee_nwk.src == 0x7c1f || zbee_nwk.dst == 0x7c1f `
- For the difference, only using deconz, with routing or not, I think it s the same workaround than hiding the time cluster, it seem the device see something missing on his parent and don't use the feature (there is only 1 report attribute when you toggle the device, but a second one when you have the issue, you can check inside the request (frame 3775) but I think you will see same attribute than here https://community.smartthings.com/t/uk-light-switches-my-experiences-2020/196035/64)
- I don't think the ZCL group part have an impact on working mode.

The cleaner method would be to let the device make the second reporting, and check what do the tuya gateway to prevent the device turn off.
And need to check if there is a special request from the tuya gateway to prevent that (but if it s not made for that, why the device make this report ?)

But BTW, you have something I haven't see before, frame 3826, the device read an attribute on the gateway, can you expend this frame pls ?

**Comment by jonnipee** [comment]
**3826**
![image](https://user-images.githubusercontent.com/58016593/124623847-ebff8780-deae-11eb-8852-500d4f80808a.png)

**Comment by SwoopX** [comment]
Can it be that the coordinator just needs to send an ordinary read response to make it work? The current code seems to hammer ALL attribte back?

**Comment by jonnipee** [comment]
is there a way to test it? or verify?

**Comment by Smanar** [comment]
Can you save the request (3834) to compare, it the deconz answer to the local time request, to compare witht he tuya gateway.

**Comment by Smanar** [comment]
Ok so @jonnipee have made a sniff with the orignal gateway. There is realy no special request
![cleansniff](https://user-images.githubusercontent.com/20152487/124639128-1429bf00-de8c-11eb-88c5-0531ccb70064.png)

He have done 3 on/off, only 1 reporting and the device stay "on"

So the "magic" happen probably during the inclusion.

Waiting to search in the sniff, someone can try this version ?

```
sudo apt install deconz-dev
git clone --branch tuya_test_1 https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

You need to re-include the problematic device.

**Comment by jonnipee** [comment]
I am currently testing this now and will report back

**Comment by jonnipee** [comment]
hi the problem still persists. 
what i noticed is that the switch initially works fine after pairing. then after 29 minutes there is a series of traffic. After this happens then the switch will turn off every 2minutes.
![image](https://user-images.githubusercontent.com/58016593/124727564-6bd63200-df41-11eb-9e2f-052a2b663c1c.png)

**Comment by Smanar** [comment]
So with @jonnipee we have probably find something, so If you want to try on your side

```
sudo apt install deconz-dev
git clone --branch tuya_test_1 https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

Or you can give at least the manufacture name of your bugged device, the PR will work ATM only for device 
- _TZ3000_fvh3pjaz

**Comment by jonnipee** [comment]
> So with @jonnipee we have probably find something, so If you want to try on your side
> 
> ```
> sudo apt install deconz-dev
> git clone --branch tuya_test_1 https://github.com/Smanar/deconz-rest-plugin.git
> cd deconz-rest-plugin
> qmake && make -j2
> sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
> ```
> 
> Or you can give at least the manufacture name of your bugged device, the PR will work ATM only for device
> 
> * _TZ3000_fvh3pjaz
> 
> PR is here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5118/files

Hi,

I am testing and so far seems ok.

Will the fix affect the following switches?
_TZ3000_wyhuocal (3 Gang tuya)
_TZ3000_9hpxg80k (1 Gang tuya)
If not can we please add them?

Thx

**Comment by Smanar** [comment]
Added the 2 others models

**Comment by jonnipee** [comment]
Hi I was just wondering if this fix has been incorporated to 2.12.4 beta thank you

**Comment by Mimiix** [comment]
The PR is still open, so it isnt

**Comment by jonnipee** [comment]
> The PR is still open, so it isnt 

Is there any eta when it will be incorporated. I used a Linux machine when I was doing testing with smanar but I'm eager to switch over to windows. 

I understand it's not the only thing you have to do. But I would appreciate it 🙏🏽

**Comment by Smanar** [comment]
I have as version the 2.13.0 or 2.13.1 from manup, but it will not help you too much.
If I m right we will have soon the next stable 2.12, so will be the next beta. Only the stable are compiled for windows ?

**Comment by jonnipee** [comment]
> I have as version the 2.13.0 or 2.13.1 from manup, but it will not help you too much.
> 
> If I m right we will have soon the next stable 2.12, so will be the next beta. Only the stable are compiled for windows ?

Understood. Thanks for all your help on this. If you are ever here in KL let me know.

**Comment by tkmamedov** [comment]
Hello!
I have the same problem with auto turn off. How could I implement the fixes from https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5118, or should I just wait for the update of deConz add-on.
I use HA with deCONZ add-on (v. 6.10.0) with Conbee Stick 2 on Raspberry PI 4.

**Comment by Smanar** [comment]
You can, but it s not easy on HA.
And I m sorry but I realy don't have ETA for PR validation, and there are so much of them

**Comment by k0rn3l** [comment]
> Hello!
> I have the same problem with auto turn off. How could I implement the fixes from #5118? Or should I just wait for the update of deConz add-on.
> I use HA with deCONZ add-on (v. 6.10.0) with Conbee Stick 2 on Raspberry PI 4.

I've managed to compile the plugin from Smanar's tuya_test_1 branch ...
AND IT WORKED!!!!
After resetting and pairing my switch with zigbee network it is behaving correctly for about 20 hours now. No auto-off behaviour :)

**Comment by jonnipee** [comment]
I hope they will add it to the beta build soon.

**Comment by tkmamedov** [comment]
> > Hello!
> > I have the same problem with auto turn off. How could I implement the fixes from #5118? Or should I just wait for the update of deConz add-on.
> > I use HA with deCONZ add-on (v. 6.10.0) with Conbee Stick 2 on Raspberry PI 4.
> 
> I've managed to compile the plugin on RPi Home Assistant OS from Smanar's tuya_test_1 branch ...
> AND IT WORKED!!!!
> After resetting and pairing my switch with zigbee network it is behaving correctly for about 20 hours now. No auto-off behaviour :)

I've compiled it too, and it worked fine for 2 gang switches (turn-off issue was resolved), but I couldn't pair my 1 gang Tuya switches after (it paired well before compiling the fixed plugin )...

**Comment by k0rn3l** [comment]
> > > Hello!
> > > I have the same problem with auto turn off. How could I implement the fixes from #5118? Or should I just wait for the update of deConz add-on.
> > > I use HA with deCONZ add-on (v. 6.10.0) with Conbee Stick 2 on Raspberry PI 4.
> > 
> > 
> > I've managed to compile the plugin on RPi Home Assistant OS from Smanar's tuya_test_1 branch ...
> > AND IT WORKED!!!!
> > After resetting and pairing my switch with zigbee network it is behaving correctly for about 20 hours now. No auto-off behaviour :)
> 
> I've compiled it too, and it worked fine for 2 gang switches (turn-off issue was resolved), but I couldn't pair my 1 gang Tuya switches after (it paired well before compiling the fixed plugin )...

I've got both models: 1- and 2- gang. No issue with paring any of them on compiled version.

**Comment by jonnipee** [comment]
1,2,3 gang work for me

**Comment by tempico** [comment]
The compiled version from an above repo seems working fine. Thank you @Smanar for your efforts!

It took about 1h to compile the ARM version on my RPI. So if anyone is interested to reuse the compiled library — just unzip the attached file into `/usr/share/deCONZ/plugins` on your RPI (take a backup of old file), restart the deCONZ app and finally re-register the switch (remove it from deCONZ and then re-pair by pressing any button on the Tuya switch for 10 seconds until the leds will be blinking).

Hope the changes will be merged to master soon.

[libde_rest_plugin.so.zip](https://github.com/dresden-elektronik/deconz-rest-plugin/files/7576892/libde_rest_plugin.so.zip)
)

**Comment by schumi2004** [comment]
> The compiled version from an above repo seems working fine. Thank you @Smanar for your efforts!
> 
> It took about 1h to compile the ARM version on my RPI. So if anyone is interested to reuse the compiled library — just unzip the attached file into `/usr/share/deCONZ/plugins` on your RPI (take a backup of old file), restart the deCONZ app and finally re-register the switch (remove it from deCONZ and then re-pair by pressing any button on the Tuya switch for 10 seconds until the leds will be blinking).
> 
> Hope the changes will be merged to master soon.
> 
> [libde_rest_plugin.so.zip](https://github.com/dresden-elektronik/deconz-rest-plugin/files/7576892/libde_rest_plugin.so.zip)

Can this also be done in HassIO?

**Comment by tempico** [comment]
> Can this also be done in HassIO?

I never used HassIO because my HA setup is too heavy for RPI. Technically there should be no problems with this if your deCONZ instance is running under ARM CPU (directly on RPI or in docker). You only have to locate the file to be replaced, replace it and make sure no official updates will be overwriting it for now.

**Comment by Smanar** [comment]
I have updated the code some days ago, because there was ugly code. Hoping for a validation for next version

**Comment by tempico** [comment]
@Smanar,
Thank you for your reply. Any chance that the changes will be merged to beta stream please?

**Comment by Smanar** [comment]
hee ... seriously I realy don't know what to say.
This PR is probalby not merged because it s theoricaly possible to do the same thing using DDF, but not sure if the code is ready for that.

You can make a try, just edit the DDF for the device, and use a basic one with absolutely nothing in the tab "binding", then make a "hot reload".

https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/DDF-cheat-sheet

**Comment by mpeterson** [comment]
@Smanar I tried doing what you mention. I did a DDF where I removed the one binding, hot reloaded and I still get the incorrect behavior of turning off after 2 minutes. IDK perhaps what I'm doing is incorrect, or perhaps it's not loading the DDF.

<img width="408" alt="image" src="https://user-images.githubusercontent.com/11870/148268853-e42686fa-d1c2-4d26-8422-d811d4c8b4c6.png">

Anyways, why is this change being held up even if it can be done with DDF? I mean, it sounds like it's a fix that everyone would be benefit from and not custom behavior.

**Comment by Smanar** [comment]
Right, and for me the DDF is good.
I will ask manup too, it s a hack but not the worst one, and as the DDF don't seem working, can take age to test.

You have tried with "strict" mode too ? (the DDF mode in "control")

**Comment by mpeterson** [comment]
@Smanar thanks for answering. I put it into "strict" mode too and still I haven't had positive results. Again, perhaps I'm doing something wrong and perhaps it's worth if you can check it too. 

Moving forward with the patch is also a good option :)

**Comment by Smanar** [comment]
I don't have device with this issue, and DDF is relay obscure for me (and it move too much for the moment)
But Manup have react on the PR, so I hope for a validation for the next version.

**Comment by donok1** [comment]
Hi @mpeterson, did you get luck with DDF ?
Apparently we can forget any hope of a merge of #5118, see #5733.

I'll have a go myself as soon as I have a bit of time, but would appreciate any hint ;)
Thanks

**Comment by HA-Jon** [comment]
I'm having the same problem. How can I rectify?

**Comment by Smanar** [comment]
It seem it can be solved with creating a DDF, but no comfirmation cf https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5118

**Comment by HA-Jon** [comment]
3a-zigbee-switch.groovy
is the file I needed, but not sure how to use it.
My switch is already installed in Home Assistant, via a Conbee USB stick.
What do I need to do?

**Comment by Smanar** [comment]
Have answered here https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5118#issuecomment-1100847247
Pls avoid making 2 times the same question on different place.

**Comment by themiskir83** [comment]
Hi all, I've done the procedure through ssh on port 22222, installed nano, new DDF file in /usr/share/deconz/devices/tuya/
rebooted the device but it keeps turning off after 2 minutes. 
VNC deconz is showing the new DDF. what is happening?

**Comment by jonnipee** [comment]
Just to note that on windows I did as smanar recommended. 
Edit DDF, removed the bindings and set to gold. I then saved the files and did hot reload. This didn't work initially. I had to then remove all the devices and re-add them and then everything worked without issue.

**Comment by Smanar** [comment]
Ha ?
I know the "magic" is set during the inclusion, but in my mind bind was verified by deconz regulary.
