### ISSUE TITLE
Support Sengled SMART LED Z01-A19NAE26

### ISSUE THREAD

**Issue by deviantintegral** [dresden-elektronik/deconz-rest-plugin#4469]
## Device

- Product name: SENGLED SMART LED: https://www.amazon.ca/Sengled-2700K-6500K-Required-Daylight-Equivalent/dp/B08KZPDK1J/ref=sr_1_7
- Manufacturer: sengled
- Model identifier: Z01-A19NAE26 (phoscon shows version 0x0000002E as well)
- Device type :
  - Light

### Clusters

<img width="395" alt="Screen Shot 2021-02-22 at 7 12 04 PM" src="https://user-images.githubusercontent.com/255023/108786568-dca42100-7541-11eb-9a24-b82cccb81c1e.png">

### Node Info

<img width="602" alt="Screen Shot 2021-02-22 at 7 11 33 PM" src="https://user-images.githubusercontent.com/255023/108786539-ce560500-7541-11eb-9deb-633ebad32962.png">

### Basic

<img width="605" alt="Screen Shot 2021-02-22 at 7 10 45 PM" src="https://user-images.githubusercontent.com/255023/108786476-af577300-7541-11eb-9592-27ec19339cd7.png">

### Identify

<img width="613" alt="Screen Shot 2021-02-23 at 6 42 40 AM" src="https://user-images.githubusercontent.com/255023/108839719-72bc6380-75a3-11eb-9357-60a348342335.png">

### Groups

<img width="596" alt="Screen Shot 2021-02-23 at 6 43 08 AM" src="https://user-images.githubusercontent.com/255023/108839810-88ca2400-75a3-11eb-8750-5047f6738bbb.png">
<img width="589" alt="Screen Shot 2021-02-23 at 6 43 32 AM" src="https://user-images.githubusercontent.com/255023/108839825-8bc51480-75a3-11eb-9907-4530c64ae574.png">

### Scenes

<img width="595" alt="Screen Shot 2021-02-23 at 6 43 59 AM" src="https://user-images.githubusercontent.com/255023/108839845-92ec2280-75a3-11eb-8c38-c69049984a9e.png">

<img width="588" alt="Screen Shot 2021-02-23 at 6 44 22 AM" src="https://user-images.githubusercontent.com/255023/108839864-98496d00-75a3-11eb-9c04-149004180d8b.png">
<img width="581" alt="Screen Shot 2021-02-23 at 6 44 35 AM" src="https://user-images.githubusercontent.com/255023/108839878-9c758a80-75a3-11eb-94c7-b45d3f9a12f5.png">

### On/Off

<img width="600" alt="Screen Shot 2021-02-23 at 6 45 00 AM" src="https://user-images.githubusercontent.com/255023/108839898-a3040200-75a3-11eb-90af-3dfe3cb2312e.png">
<img width="583" alt="Screen Shot 2021-02-23 at 6 45 16 AM" src="https://user-images.githubusercontent.com/255023/108839920-a8f9e300-75a3-11eb-9a8a-75ffc5c8fe50.png">

### Level Control
<img width="587" alt="Screen Shot 2021-02-23 at 6 45 35 AM" src="https://user-images.githubusercontent.com/255023/108839940-adbe9700-75a3-11eb-9da8-0d7bb296041e.png">
<img width="584" alt="Screen Shot 2021-02-23 at 6 45 54 AM" src="https://user-images.githubusercontent.com/255023/108839968-b31be180-75a3-11eb-94b5-be3498c5ce56.png">

### Color Control
<img width="588" alt="Screen Shot 2021-02-23 at 6 46 30 AM" src="https://user-images.githubusercontent.com/255023/108839976-b7e09580-75a3-11eb-8199-07e982d02829.png">
<img width="589" alt="Screen Shot 2021-02-23 at 6 46 43 AM" src="https://user-images.githubusercontent.com/255023/108839985-bb741c80-75a3-11eb-901d-48ba1cc5d143.png">
<img width="589" alt="Screen Shot 2021-02-23 at 6 47 17 AM" src="https://user-images.githubusercontent.com/255023/108839994-be6f0d00-75a3-11eb-9fc1-60340e50d63e.png">
<img width="575" alt="Screen Shot 2021-02-23 at 6 47 42 AM" src="https://user-images.githubusercontent.com/255023/108840008-c2029400-75a3-11eb-9cd6-20b53e5a10e4.png">
<img width="584" alt="Screen Shot 2021-02-23 at 6 47 54 AM" src="https://user-images.githubusercontent.com/255023/108840025-c7f87500-75a3-11eb-904e-8a6acb62e0ee.png">

### Simple Metering

<img width="606" alt="Screen Shot 2021-02-23 at 6 48 20 AM" src="https://user-images.githubusercontent.com/255023/108840053-d21a7380-75a3-11eb-8136-a4bae08985c3.png">

### Diagnostics

<img width="609" alt="Screen Shot 2021-02-23 at 6 48 44 AM" src="https://user-images.githubusercontent.com/255023/108840066-d5adfa80-75a3-11eb-8bbb-d4b97f2e36f0.png">

As is, I can control brightness in Phoscon. I can control light temperature in deconz, though it's showing the bulb as if it supports full RGB. Those commands error out if tried.

From the REST API (the light is currently off at the switch)

```
  "5": {
    "etag": "adcc136c87b705f2f20177919eba6fa3",
    "hascolor": true,
    "lastannounced": null,
    "lastseen": "2021-02-23T01:27Z",
    "manufacturername": "sengled",
    "modelid": "Z01-A19NAE26",
    "name": "Kitchen Hallway 1",
    "state": {
      "alert": "none",
      "bri": 254,
      "colormode": "ct",
      "on": false,
      "reachable": false
    },
    "swversion": "0x0000002E",
    "type": "Dimmable light",
    "uniqueid": "b0:ce:18:14:03:00:f9:92-01"
  },
```

**Comment by Mimiix** [comment]
Missing screenshots from other clusters.

**Comment by deviantintegral** [comment]
Done! I think I misunderstood what screenshots were required from the issue template. I'll file a followup.

**Comment by deviantintegral** [comment]
An aside for anyone else reading this; while temperature controls don't show up in Phoscon or Home Assistant's UI, I am able to change the colour by calling the `light.turn_on` service with `kelvin` set. I just verified that the lights work with the `flux` integration too. As long as you don't need manual control of temperature, I'd say these lights are good enough to purchase given their low price in bulk at $14.25 CDN / bulb.

**Comment by stevewull** [comment]
@Mimiix: I posted the screenshots of all clusters, including all of the attributes for the color control cluster, in issue #4536. Hopefully, it provides the info you requested.

I confirm that behavior is the same for me as deviantintegral: temperature controls don't show up in Phoscon or Home Assistant's UI, but I am able to change the color by calling the light.turn_on service.

**Comment by stevewull** [comment]
I just installed v.2,10.4 Tortuga.  This issue is not resolved. API still does not have the ct value:

![image](https://user-images.githubusercontent.com/46251961/113302564-0e34a880-92b5-11eb-8024-62f078b64dd7.png)

**Comment by kaisamng** [comment]
The pull request for this only adds a kWh metering element for Z01-A19NAE26, not an element for adjusting color temperature manually. Unfortunately, the workaround that @deviantintegral on calling the service manually fails. 

Currently through Phoscon, adjusting the brightness changes _both_ the color temperature and the brightness of these bulbs. 

Is there any plan to support a color temperature option, separate from brightness, for these bulbs?
