### ISSUE TITLE
Woox R7049 Smoke Alarm

### ISSUE THREAD

**Issue by andwari** [dresden-elektronik/deconz-rest-plugin#4693]
### Device
    Product name: Woox R7049 Smoke Alarm
    Manufacturer: _TZE200_aycxwiau
    Model identifier: TS0601
    Device type:
        Other: Smoke Alarm

Product page: https://wooxhome.com/products-c10/security-c6/r7049-smoke-alarm-single-unit-p70
### Node Info
![01_Woox_SmokeSensor_Node_Info](https://user-images.githubusercontent.com/9388370/113477868-5a364780-9485-11eb-9551-9ea24e3cee10.png)

### Basic Cluster
![02_Woox_SmokeSensor_Basic_1](https://user-images.githubusercontent.com/9388370/113477879-69b59080-9485-11eb-8007-08f0c470bc4f.png)
![03_Woox_SmokeSensor_Basic_2](https://user-images.githubusercontent.com/9388370/113477880-6a4e2700-9485-11eb-833f-1070a05beb69.png)

### Groups
![04_Woox_SmokeSensor_Groups](https://user-images.githubusercontent.com/9388370/113477926-d7fa5300-9485-11eb-8132-8f292c33ac4d.png)

### Scenes
![05_Woox_SmokeSensor_Scenes](https://user-images.githubusercontent.com/9388370/113477933-e47eab80-9485-11eb-81fb-045deef2428c.png)

### Tuya specific Cluster
![06_Woox_SmokeSensor_Tuya](https://user-images.githubusercontent.com/9388370/113477939-ee081380-9485-11eb-9370-6fdc79a14e63.png)

### OTAU
![07_Woox_SmokeSensor_OTAU_1](https://user-images.githubusercontent.com/9388370/113477944-f9f3d580-9485-11eb-8479-5098fb2a8d6f.png)
![08_Woox_SmokeSensor_OTAU_2](https://user-images.githubusercontent.com/9388370/113477945-fa8c6c00-9485-11eb-90eb-7e7ddd46903f.png)

### Time
![09_Woox_SmokeSensor_Time](https://user-images.githubusercontent.com/9388370/113477949-01b37a00-9486-11eb-9f49-739df82fde09.png)

**Comment by valentingc** [comment]
I'd also love to see this device being supported. Seems this is the only Zigbee based smoke detector that has great availability where I live, and it is quite affordable.

**Comment by andwari** [comment]
Bump

**Comment by air2** [comment]
Could this issue be reopened, I would love to see support for this device

**Comment by Mimiix** [comment]
Sure

**Comment by valentingc** [comment]
@Mimiix Could this issue please be reopened?

**Comment by Mimiix** [comment]
@valentingc sure.

Please keep it open yourselves by bumping it

**Comment by Smanar** [comment]
Hello, do you have a linux machine with full OS to test code modifications ?

**Comment by andwari** [comment]
@Smanar I have a linux machine and can test some code modifications

**Comment by Smanar** [comment]
So it s the first tuya smoke sensor, so I m not sure for result

You have the procedure here https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Compiling-the-REST-plugin-for-device-specific-testing
So for you, after having installed deconz :

```
sudo apt install deconz-dev
git clone --branch woox_smoke https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

Then re include the device.

**Comment by andwari** [comment]
@Smanar Thank you very much. It seems that the sensor is now recognized by deconz as fire sensor. Though it does not appear in the phoscon webapp, it seems that the sensor is accessible via the REST API (which is more or less all I need). Once again, thank you very much

**Comment by aaronerhart** [comment]
@Smanar 
Sorry I am new here. Will it be possible in the future to integrate the R7049 also via the phoscon app?

**Comment by Smanar** [comment]
@andwari so it work on first try ? I can make the PR ?

@aaronerhart ATM we are realy late on PR validation, so IDK when it will be available on deconz, and make phoscon use it is another thing.

You can ask on phoscon github when the device will be in deconz.

**Comment by valentingc** [comment]
@Smanar Thanks for your awesome work! Looking forward to the PR, I was waiting to buy the device until there was deconz support.


@andwari Could you maybe if you get to it test-trigger the smoke detector to check whether the fire state is also correctly mapped in the REST API? Seems to me like we should test that too for such kind of a device.

**Comment by andwari** [comment]
@valentingc You are absolutely right. I will test it as soon as possible but maybe not today (or my neighbors will kill me ;) ).

**Comment by valentingc** [comment]
Bump

**Comment by timvdsm** [comment]
Hi, I can see the status of the Woox R7049 smoke alarm, however I don't see the battery level. Is it possible to add this also, as this is pretty interesting information.

**Comment by Smanar** [comment]
This device don't have battery level, but it need to have a lowbattery notification in the json ?

**Comment by timvdsm** [comment]
> This device don't have battery level, but it need to have a lowbattery notification in the json ?

Indeed, that’s what I wanted to ask, to know when the battery is low. The information should be there, because it’s available in other zigbee platforms (as dell as link quality). Would be great to have this additional information in deconz.

**Comment by Smanar** [comment]
>because it’s available in other zigbee platforms

Wich one ?
My reference is z2m, ant they haven't it too https://www.zigbee2mqtt.io/devices/R7049.html

**Comment by timvdsm** [comment]
> Wich one ? My reference is z2m

Indeed z2m, here you have smoke, battery_low, linkquality. It's the battery_low and linkquality which I absolutely want to add in Home Assistant. However it only exposes for me if smoke is detected or not.

**Comment by Smanar** [comment]
>Or is there any way to get the battery_low and linquality?

Link quality are not exposed in the API.
But the low battery need to be in the JSON, can you take a look in phoscon / hep / api information to see the complete device json ?

**Comment by timvdsm** [comment]
Hi @Smanar 

        "2": {
            "config": {
                "on": true,
                "reachable": true
            },
            "ep": 1,
            "etag": "790b0b696d9d4dc5305aa5d4e7b11d09",
            "lastannounced": "2021-12-23T22:49:20Z",
            "lastseen": "2021-12-25T09:38Z",
            "manufacturername": "_TZE200_aycxwiau",
            "modelid": "TS0601",
            "name": "Fire 2",
            "state": {
                "fire": null,
                "lastupdated": "none",
                "lowbattery": null
            },
            "type": "ZHAFire",
            "uniqueid": "5c:02:72:ff:fe:90:46:9a-01-ef00"
        },

So indeed ... I see  mentioned "lowbattery": null ... which I suppose will be active when the battery is low. Any idea to get this into Home Assistant? I installed the deconz integration, which connects to my Phoscon GW. And it automatically exposes the smoke detector as a binary sensor in Home Assistant. Now I just need an additional one for the battery low indication. 

And by the way ... many thanks for your hard work on this. This really makes a difference for many people like me to have a life saving device locally integrated in Home Assistant! It's absolutely appreciated!

**Comment by Smanar** [comment]
Ha, it s perhaps because the value is "null", for HA the value need to be true or false ?
If @Robban can confirm ?

**Comment by Kane610** [comment]
Home assistant integration does not generate sensors for low_battery. And I guess the logic would expect it to be True/False rather than null.

**Comment by Smanar** [comment]
Ha yes right, there is something bugged
```
            else if (sensor.fingerPrint().hasInCluster(TUYA_CLUSTER_ID))
            {
                clusterId = clusterId ? clusterId : TUYA_CLUSTER_ID;
                sensor.addItem(DataTypeBool, RStateLowBattery)->setValue(false);
            }
```

**Comment by timvdsm** [comment]
> Home assistant integration does not generate sensors for low_battery. And I guess the logic would expect it to be True/False rather than null.

Any way to get it in HA through a workaround?

**Comment by timvdsm** [comment]
> Right, and there is something bugged
> 
> ```
>             else if (sensor.fingerPrint().hasInCluster(TUYA_CLUSTER_ID))
>             {
>                 clusterId = clusterId ? clusterId : TUYA_CLUSTER_ID;
>                 sensor.addItem(DataTypeBool, RStateLowBattery)->setValue(false);
>             }
> ```
> 
> It need to be false at startup

Does this mean, it could be solved? 😁

**Comment by Smanar** [comment]
>Does this mean, it could be solved? 😁

Not realy ^^.
ATM update can be only done with DDF, but it will not change something for you as you need to make something in HA to manage the lowbattery state.

**Comment by Electronisse** [comment]
> @valentingc You are absolutely right. I will test it as soon as possible but maybe not today (or my neighbors will kill me ;) ).

Did you get around to testing it?

I tried to add mine to deconz today.
The smoke detector shows up and everything, so i tried to trigger it with some smoke.
The state/fire does never change for me, its false when the device is first added, and becomes null after restart of deconz.
This is the response i get, both with and without smoke:

`
{
    "config": {
        "on": true,
        "reachable": true
    },
    "ep": 1,
    "etag": "18829250289984f542f34f4634d21415",
    "lastannounced": null,
    "lastseen": "2022-01-06T22:51Z",
    "manufacturername": "_TZE200_aycxwiau",
    "modelid": "TS0601",
    "name": "Fire 50",
    "state": {
        "fire": null,
        "lastupdated": "none",
        "lowbattery": null
    },
    "type": "ZHAFire",
    "uniqueid": "bc:33:ac:ff:fe:26:e2:0d-01-ef00"
}
`

**Comment by Kane610** [comment]
> > Home assistant integration does not generate sensors for low_battery. And I guess the logic would expect it to be True/False rather than null.
> 
> Any way to get it in HA through a workaround?

The issue is that right now all sensor devices would get a low_battery entity if default values is None since its not possible to differentiate between devices supporting reporting low_battery with devices not supporting it

**Comment by km8742** [comment]
> > @valentingc You are absolutely right. I will test it as soon as possible but maybe not today (or my neighbors will kill me ;) ).
> 
> @andwari Did you get around to testing it?
> 
> I tried to add mine to deconz today. The smoke detector shows up and everything, so i tried to trigger it with some smoke. The state/fire does never change for me, its false when the device is first added, and becomes null after restart of deconz. This is the response i get, both with and without smoke:
> 
> `{ "config": { "on": true, "reachable": true }, "ep": 1, "etag": "18829250289984f542f34f4634d21415", "lastannounced": null, "lastseen": "2022-01-06T22:51Z", "manufacturername": "_TZE200_aycxwiau", "modelid": "TS0601", "name": "Fire 50", "state": { "fire": null, "lastupdated": "none", "lowbattery": null }, "type": "ZHAFire", "uniqueid": "bc:33:ac:ff:fe:26:e2:0d-01-ef00" }`

Same problem here, I was able to register 3 smoke detectors R7049 - they're showing up in the websocket with updates. Not showing up in Phoscon webfrontend and not showing an alarm on trigger.

One of three showing fire:null - the other fire:false if I go over the webapi /sensors page.

**Comment by Smanar** [comment]
Even if you restart deconz ? It seem it need to use a default value for this kind of sensor

```
            item = sensor.addItem(DataTypeBool, RStateFire);
            item->setValue(false);
```

`"lastseen": "2022-01-06T22:51Z"`

It haven't disconnecvted ?

**Comment by km8742** [comment]
> Even if you restart deconz ? It seem it need to use a default value for this kind of sensor
> 
> ```
>             item = sensor.addItem(DataTypeBool, RStateFire);
>             item->setValue(false);
> ```
> 
> `"lastseen": "2022-01-06T22:51Z"`
> 
> It haven't disconnected ?

After a reboot all three fire sensors show fire:null and lowbattery:null.

In the websocket I get events, lastseen is updated.

In the API I have config: on: true / reachable: true.

**Comment by Smanar** [comment]
>In the websocket I see events, lastseen is updated.

for third ?

**Comment by km8742** [comment]
> > In the websocket I see events, lastseen is updated.
> 
> for third ?

For all of them.
I use the websocket to read all events.

All three smoke sensors give events - so they have to be registered, right? But no event is fired when the smoke sensor goes off.

Sample (uniqueID changed):
`{"attr":{"id":"12","lastannounced":null,"lastseen":"2022-01-16T14:10Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 12","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"12","r":"sensors","t":"event","uniqueid":"Sensor01"}

{"attr":{"id":"11","lastannounced":"2022-01-15T11:25:00Z","lastseen":"2022-01-16T14:10Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor02"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor02"}

{"attr":{"id":"13","lastannounced":null,"lastseen":"2022-01-16T14:10Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 13","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor03"},"e":"changed","id":"13","r":"sensors","t":"event","uniqueid":"Sensor03"}
`

**Comment by Smanar** [comment]
>But no event is fired when the smoke sensor goes off

I think you have something displayed in HA if the device become unreachable (HA probably use config/reachable based on last seen) ?

But after some time, you need to have state/fire = False ? And those devices don't have a "test" button ?

**Comment by km8742** [comment]
I'm not using HA - I'm only using deconz installed on a headless PI.
I'm using the websocket service to check for events (fire:true and so on).
I can test the smoke alarms by long pressing a button, will try but I don't think there will be any difference to a real alarm.

**Comment by Smanar** [comment]
Just to be sure you haven't a "light" entry for this device ?

I m seing 2 possibles issues.
- the device don't trigger event at all and it need (new firmware with exotic pairing ...)
- the device don't trigger event at all and it's normal (realy lazy one)

If you test the smoke alarm, the device will obligatory send an event, if you still have state/fire = null and lastupdated = null, I think it s the first one. Can you check if "lastseen" update something too.

**Comment by km8742** [comment]
I've triggered the manual alarm:
16:40	Testart 
`	API Output: {"config":{"on":true,"reachable":true},"ep":1,"etag":"f8dec922b7a7c034901957e8d70613d9","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T16:39Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","state":{"fire":null,"lastupdated":"none","lowbattery":null},"type":"ZHAFire","uniqueid":"Sensor01"}
`
16:46	Testalarm
	`API Output: {"config":{"on":true,"reachable":true},"ep":1,"etag":"2bbb9db03fcdc73b54915132ae2d943a","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T16:45Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","state":{"fire":null,"lastupdated":"none","lowbattery":null},"type":"ZHAFire","uniqueid":"Sensor01"}
`

17:29 After
`{"config":{"on":true,"reachable":true},"ep":1,"etag":"e6f0261dd063c099a32ac02fbbcef6aa","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:28Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","state":{"fire":null,"lastupdated":"none","lowbattery":null},"type":"ZHAFire","uniqueid":"Sensor01"}
`
Events from websocket:
```
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T16:39Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T16:40Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T16:41Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T16:42Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T16:43Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T16:44Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T16:45Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T16:46Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T16:47Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T16:48Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T16:49Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T16:50Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T16:51Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T16:52Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T16:53Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T16:54Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T16:55Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T16:56Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T16:57Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T16:59Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:00Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:01Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:02Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:03Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:04Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:05Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:06Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:07Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:08Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:09Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:10Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:11Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:12Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:13Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:14Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:15Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:16Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:17Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:18Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:19Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:20Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:21Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:22Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:23Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:24Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:25Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:26Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:27Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:28Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:29Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:30Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:31Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:32Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-18T17:33Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"Sensor01"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"Sensor01"}

```

Currently I dont care about lastseen (my code currently does not check this) but this value is getting updated.
The most important thing is that I get an event when the fire alarm goes off (similar to presence:true with ikea motion detectors) so my software can trigger an alarm - this is triggered trough the websocket - because it's much faster, not by pinging the API sensor values.

I could not find any firmware updates on the site of woox.

So do you think this is not possible without the app & gateway of woox or is this a work in progress on the side of deconz?

Thanks a lot for your time!

**Comment by Smanar** [comment]
I think you will not like what I m going to say, but I realy need some logs.

With flag "info" and "info_l2".

All tuya request are logged so we will be able to see all requests from the device. It make request because it update the "lastseen", it 's a good news, but it don't update the battery or the fire detection, so I don't see what it can be, and 1 report every minut is a lot for me, I don't think it's good for battery.

**Comment by km8742** [comment]
Is it enough to start deconz service with the following flags?
--dbg-info=2 --dbg-zdp=1 --dbg-zcl=1 --db-aps=1 --dbg-http=1

**Comment by Smanar** [comment]
Just `--dbg-info=2`
And if you are headless `-platform minimal`

**Comment by km8742** [comment]
That's a lot of data. What time window of log file would you need? And how can I send it to you?

**Comment by Smanar** [comment]
If you use the button to simulate the fire, I just need the log during the procedure (so 1/2 min logs)
If you can filter, I just need log with "Tuya debug"

And you can use the hotst you want, or just make a c/c here if you can find the tuya logs made by this device specially.

**Comment by km8742** [comment]
First off I have seen that two of the three smoke sensors have the same mac address - is that possible?
The only difference in the uniqueid is the last 10 digits - and as far I know those are additionally added right?

Triggered a test alarm with the button on 13:40

```
13:35:28:463 No Tuya productId entry found for manufacturername: _TZ3000_nwpihrkp
13:35:28:680 Tuya debug 7 : Missing manufacture name for 0xSENSOR01
13:35:28:682 No Tuya productId entry found for manufacturername: _TZ3000_nwpihrkp
13:35:28:683 No Tuya productId entry found for manufacturername: _TZ3000_nwpihrkp
13:35:28:684 No Tuya productId entry found for manufacturername: _TZ3000_nwpihrkp
13:35:28:686 Tuya debug 7 : Missing manufacture name for 0xSENSOR01
13:35:28:687 No Tuya productId entry found for manufacturername: _TZ3000_nwpihrkp
13:35:28:688 No Tuya productId entry found for manufacturername: _TZ3000_nwpihrkp
13:35:28:689 No Tuya productId entry found for manufacturername: _TZ3000_nwpihrkp
13:35:28:691 Tuya debug 7 : Missing manufacture name for 0xSENSOR02
13:35:28:694 Tuya debug 7 : Missing manufacture name for 0xSENSOR02
13:35:28:703 Tuya debug 7 : Missing manufacture name for 0xSENSOR03
13:35:28:706 Tuya debug 7 : Missing manufacture name for 0xSENSOR03
13:35:28:720 Tuya debug 7 : Missing manufacture name for 0xSENSOR04
13:35:28:723 Tuya debug 7 : Missing manufacture name for 0xSENSOR04
13:36:07:654 Tuya debug Request : Address 0xSENSOR02, Endpoint 0x01, Command 0x01, Payload 001e0801000101
13:36:07:654 Tuya debug 4 : Address 0xSENSOR02 Payload 001e0801000101
13:36:07:654 Tuya debug 5 : Status: 0 Transid: 30 Dp: 264 (0x01,0x08) Fn: 0 Data 1
13:36:15:580 Tuya debug Request : Address 0xSENSOR02, Endpoint 0x01, Command 0x01, Payload 001f0904000101
13:36:15:580 Tuya debug 4 : Address 0xSENSOR02 Payload 001f0904000101
13:36:15:580 Tuya debug 5 : Status: 0 Transid: 31 Dp: 1033 (0x04,0x09) Fn: 0 Data 1
13:36:17:718 Tuya debug Request : Address 0xSENSOR02, Endpoint 0x01, Command 0x01, Payload 00200801000100
13:36:17:718 Tuya debug 4 : Address 0xSENSOR02 Payload 00200801000100
13:36:17:718 Tuya debug 5 : Status: 0 Transid: 32 Dp: 264 (0x01,0x08) Fn: 0 Data 0
13:40:04:694 Tuya debug Request : Address 0xSENSOR02, Endpoint 0x01, Command 0x01, Payload 00210801000101
13:40:04:694 Tuya debug 4 : Address 0xSENSOR02 Payload 00210801000101
13:40:04:694 Tuya debug 5 : Status: 0 Transid: 33 Dp: 264 (0x01,0x08) Fn: 0 Data 1
13:40:12:538 Tuya debug Request : Address 0xSENSOR02, Endpoint 0x01, Command 0x01, Payload 00220904000101
13:40:12:538 Tuya debug 4 : Address 0xSENSOR02 Payload 00220904000101
13:40:12:538 Tuya debug 5 : Status: 0 Transid: 34 Dp: 1033 (0x04,0x09) Fn: 0 Data 1
13:40:14:674 Tuya debug Request : Address 0xSENSOR02, Endpoint 0x01, Command 0x01, Payload 00230801000100
13:40:14:674 Tuya debug 4 : Address 0xSENSOR02 Payload 00230801000100
13:40:14:674 Tuya debug 5 : Status: 0 Transid: 35 Dp: 264 (0x01,0x08) Fn: 0 Data 0
```

**Comment by Smanar** [comment]
>First off I have seen that two of the three smoke sensors have the same mac address - is that possible?

No, You are sure of you ?

>The only difference in the uniqueid is the last 10 digits - and as far I know those are additionally added right?

10 ?
The unique ID is composed buy the mac adress - endpoint (2 digit)- cluster (4 digit)

Ok so from logs, it can be
>13:36:07:654 Tuya debug 5 : Status: 0 Transid: 30 Dp: 264 (0x01,0x08) Fn: 0 Data 1

With data = 1 then 0. And this request is missing in code, but it s the "test" feature command

>13:36:15:580 Tuya debug 5 : Status: 0 Transid: 31 Dp: 1033 (0x04,0x09) Fn: 0 Data 1

With data always = 1. And this request is missing too, and have no clue what is it.

On the code (at the base) this device need to use (0x01 0x01) as command for fire detection.

So bad luck, the device use different request for "fire" and "test" ....

On your logs you don't have a periodic "Tuya debug" for this device ? I think you have a 0x01 0x01 but with value 0 (To mean no fire)
If you can see it, I have found the issue and all is normal.

**Comment by km8742** [comment]
Sorry - I just saw that the last two chars after the ':' also belong to the mac address - so no dupes there.

Searched for all messages containing 0x01 and this MAC Address in the log:
`14:03:35:591 Tuya debug Request : Address 0xSENSOR01, Endpoint 0x01, Command 0x24, Payload 00ae
15:04:19:962 Tuya debug Request : Address 0xSENSOR01, Endpoint 0x01, Command 0x24, Payload 00af
16:05:04:198 Tuya debug Request : Address 0xSENSOR01, Endpoint 0x01, Command 0x24, Payload 00b0
16:08:46:298 [WARNING] - Missing cluster in sensor fingerprint: 0xSENSOR01 - 0xE36F (TS0601), endpoint: 0x01, cluster: 0x000A, payload: 0700, zclSeq: 95
17:05:48:431 Tuya debug Request : Address 0xSENSOR01, Endpoint 0x01, Command 0x24, Payload 00b1
18:04:40:470 Tuya debug Request : Address 0xSENSOR01, Endpoint 0x01, Command 0x01, Payload 000d0e04000102
18:06:32:617 Tuya debug Request : Address 0xSENSOR01, Endpoint 0x01, Command 0x24, Payload 00b2
19:07:16:866 Tuya debug Request : Address 0xSENSOR01, Endpoint 0x01, Command 0x24, Payload 00b3
20:08:01:135 Tuya debug Request : Address 0xSENSOR01, Endpoint 0x01, Command 0x24, Payload 00b4
`

**Comment by Smanar** [comment]
It's not "0xSENSOR02" from your previous log ?

>18:04:40:470 Tuya debug Request : Address 0xSENSOR01, Endpoint 0x01, Command 0x01, Payload 000d0e04000102

Payload 000d0e04000102 > 00 0d 0e04 00 01 02 So it's the Command 0x04 0x0e
It's the battery level
```
0 2 above 2,8v
0 1 above 2.6v
0 0 at 2.6v and below (beeps ocassionally)
```
I m wrong I m using 0x02 so I need to correct that
And I m wro,g too for the fire detection ...

BTW if you have not make mistake with the device (if it s realy the 0xSENSOR01) I can correct the battery level and use it as heartbeat.
So everytime you will see a battery report, it will update those 2 fields
```
            "lastupdated": "none",
            "lowbattery": null
```

The last seen will be corrected by this PR https://github.com/dresden-elektronik/deconz-rest-plugin/pull/5675 if manup is agree to add the tuya cluster.

and ofc I can correct the fire detection for fire = null (I m using 0x01 0x01 and need to use 0x04 0x01)

Now the big question, have you a linux machine with full OS to test code change ?

**Comment by km8742** [comment]
I have not extracted the sensor data of the one which I did the alarm test - but it all are the same sensor.

I'm running the USB Stick with a Raspberry PI - deconz is installed trough the APT Release path. 
I could theoretically set up a test machine to test only the fire detector so my setup won't get lost on the PI.

**Comment by Smanar** [comment]
Yes, you can use a test machine, else don't worry, the procedure don't impact your database and change only 1 file, so you can make a backup of it **in another folder.**

You have the procedure here https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Compiling-the-REST-plugin-for-device-specific-testing
So for you, after having installed deconz (The code is based on realy last one):

```
sudo apt install deconz-dev
git clone --branch woox_fix https://github.com/Smanar/deconz-rest-plugin.git
cd deconz-rest-plugin
qmake && make -j2
sudo cp ../libde_rest_plugin.so /usr/share/deCONZ/plugins
```

If you have a small raspberry, it can freeze during compilation, my pi 3 do, so remove "-j2"

No need to re-include the device.

**Comment by km8742** [comment]
Did it and worked perfectly! The fire test triggered a websocket message!
Still not showing up in the Phoscon app though.

Do you need any logs for further data?

**Comment by Smanar** [comment]
For information even the test feature now trigger a fire detection.
If all is fine for you, will make the PR

**Comment by Kane610** [comment]
Can you share websocket examples of these different events @Smanar

**Comment by Smanar** [comment]
I don't t have the device but it s like all other sensor : state/fire = true

**Comment by km8742** [comment]
Here are the websocket events with the fire alarm:
```
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-23T15:21Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","swversion":null,"type":"ZHAFire","uniqueid":"SENSOR"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"SENSOR"}
{"e":"changed","id":"11","r":"sensors","state":{"fire":true,"lastupdated":"2022-01-23T15:22:03.284","lowbattery":null},"t":"event","uniqueid":"SENSOR"}
{"e":"changed","id":"11","r":"sensors","state":{"fire":false,"lastupdated":"2022-01-23T15:22:19.579","lowbattery":null},"t":"event","uniqueid":"SENSOR"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-23T15:22Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"SENSOR"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"SENSOR"}
{"attr":{"id":"11","lastannounced":"2022-01-18T16:38:46Z","lastseen":"2022-01-23T15:23Z","manufacturername":"_TZE200_aycxwiau","modelid":"TS0601","name":"Fire 11","productid":"Tuya_OTH R7049 Smoke Alarm","swversion":null,"type":"ZHAFire","uniqueid":"SENSOR"},"e":"changed","id":"11","r":"sensors","t":"event","uniqueid":"SENSOR"}

```

Will the rest changes get discarded if I do an apt update or will these updates be included in the next release?

**Comment by Smanar** [comment]
>Will the rest changes get discarded if I do an apt update or will these updates be included in the next release?

Good question, I will ask to mimiix, but you can can check if the PR is validated or not before making an update.

**Comment by km8742** [comment]
Will do - thanks!

**Comment by Electronisse** [comment]
Downloaded the woox_fix branch today and tested again.
This now works for me as well, all the way through to home assistant and node red.
Thanks for great work :)

BUT the fire state is inverted for me, shows true in postman and home assistant when there is no smoke, goes false when smoke is detected.

Atleast home assistant seems to expect the opposite of this, true when smoke detected.

**Comment by Smanar** [comment]
Arf too, late ...
The PR is merged.

The issue happen only on fire detection or the "test" button too ?

**Comment by Electronisse** [comment]
Ah damn, didnt have opportunity to try before now.

I checked, the issue is only with fire detection, and not with the test button.
After press test button, the flag is true while alarm/test is going, and flag becomes false after test is finished.
But real smoke sets flag false when smoke detected, and flag true when smoke is gone.

I tried to fix it locally by flipping "bool fire = (data==0) ? false:true;" to "true:false" in tuya.cpp before compiling. That fixed it for me.

**Comment by Smanar** [comment]
Have made a short PR
